// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/smousa/chatty/design
// --out=$(GOPATH)/src/github.com/smousa/chatty
// --version=v1.1.0-dirty
//
// API "chatty": message Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"bytes"
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// ParseMessagePayload is the message parse action payload.
type ParseMessagePayload struct {
	Input string `form:"input" json:"input" xml:"input"`
}

// ParseMessagePath computes a request path to the parse action of message.
func ParseMessagePath() string {

	return fmt.Sprintf("/api/messages")
}

// Extract message info from message
func (c *Client) ParseMessage(ctx context.Context, path string, payload *ParseMessagePayload, contentType string) (*http.Response, error) {
	req, err := c.NewParseMessageRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewParseMessageRequest create the request corresponding to the parse action endpoint of the message resource.
func (c *Client) NewParseMessageRequest(ctx context.Context, path string, payload *ParseMessagePayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType != "*/*" {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
