// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/smousa/chatty/design
// --out=$(GOPATH)/src/github.com/smousa/chatty
// --version=v1.1.0-dirty
//
// API "chatty": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
